"""move is_active to users table

Revision ID: 575ff522ebc0
Revises: 84dcf53a5b91
Create Date: 2023-10-03 19:07:22.055100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '575ff522ebc0'
down_revision: Union[str, None] = '84dcf53a5b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'is_active')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('student', 'teacher'),
               type_=sa.Enum('teacher', 'student', name='role'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('teacher', 'student', name='role'),
               type_=mysql.ENUM('student', 'teacher'),
               existing_nullable=True)
    op.drop_column('users', 'is_active')
    op.add_column('profiles', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
